### ISSUE TITLE
Create PAT to trigger ruby-rnp workflow from rnp master workflow

### ISSUE THREAD

**Issue by maxirmx** [rnpgp/ruby-rnp#87]
In order to trigger ruby-rnp workflow from rnp master workflow  Personal Access Token is required
It shall be created in this (ruby-rnp) repository and added as a secret to rnp repository
(https://github.com/peter-evans/repository-dispatch#token)

**Comment by ronaldtse** [comment]
Added as `RNP_CI_PAT_TOKEN`.

**Comment by maxirmx** [comment]
@ronaldtse
It says `token has insufficient permissions`
Could you please recreate it with public_repo scope as shown below:

![image](https://user-images.githubusercontent.com/2081498/229602981-dd9427ff-296b-4991-9857-8fdd453920d3.png)

That worked in my tests.
Thank you

**Comment by ronaldtse** [comment]
@maxirmx the current token already has the said permission. Could it be that the token name is not set correctly and hence reading an empty token?

<img width="271" alt="Screenshot 2023-04-05 at 8 21 03 AM" src="https://user-images.githubusercontent.com/11865/229943456-d24d5621-fa9e-46b2-b822-6e0f72753a99.png">

**Comment by maxirmx** [comment]
With this token GHA triggers php-rnp but fails to trigger ruby-rnp. So the issue is not related to the token or rnp workflow.

Also it triggers ruby-rnp from my personal workflow using my personal token so the issue seems not to be related to ruby-rnp workflow either.

Now it looks like a mistery

**Comment by ronaldtse** [comment]
With your latest hint I found out the the Ruby-RNP repository did not provide the CI user with write permissions, and it’s now fixed. Hope it works now!

**Comment by maxirmx** [comment]
Thank you, @ronaldtse 
It works !
